language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install emacs-24.3-bin
  - evm install $EVM_EMACS --use
  - cask
  - EMACS=$(evm bin emacs-24.3-bin) make start-server
env:
  - EMACS=emacs-23.4
  - EMACS=emacs-24.1
  - EMACS=emacs-24.2
  - EMACS=emacs-24.3
script:
  - make test
after_failure:
  - cat servant/tmp/servant.log
after_script:
  - make stop-sever
