language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs24-nox emacs24-el emacs24-common-non-dfsg
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-nox;
    fi
  # There is no need for running this as `make ecukes` automatically does it.
  # However, it makes Travis CI log cleaner and failure in `make elpa` is
  # counted as non-test failure (the gray icon).
  - make elpa
  # Start server with Emacs 24, as elnode does not support 23.
  - make EMACS=emacs24 start-server
env:
  - EMACS=emacs-snapshot
  - EMACS=emacs24
  - EMACS=emacs23
script:
  - $EMACS --version
  - make smoke
  - make ecukes
  # Test go script:
  - curl -fsSkL https://raw.github.com/rejeep/carton/master/go | sh
after_failure:
  - cat tmp/server.log
after_script:
  - make stop-sever
