language: emacs-lisp
before_install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  # There is no need for running this as `make unit` automatically does it.
  # However, it makes Travis CI log cleaner and failure in `make elpa` is
  # counted as non-test failure (the gray icon).
  - make elpa
env:
  - EMACS=emacs24
script:
  - make unit
  # Test go script:
  - curl -fsSkL https://raw.github.com/rejeep/carton/master/go | sh
